language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install libv4l-0 libv4l-dev libopencv-dev libopencv-core2.3 libopencv-core2.3-dev

before_script:
  - cmake .

script:
  - make

notifications:
  email:
    on_success: change
    on_failure: always
