language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update

install:
  - sudo apt-get install libv4l-0 libv4l-dev libcv-dev libopencv-dev libboost-all-dev

before_script:
  - cmake .

script:
  - make

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - secure: "qv1TfmSmWAsitSK46t88KmjDCfRCE1psIHKrpdu8iccBsgE7k6M4MBaIbEWu2QG+4gFBXp+xJKl0OFI+Lsnz1+JyvVf3EHSVNGDhUduQcCTFPRnJseT+DNBxfPiSTxDiv5FiDtU28c8iCVC85of7CbqaRG4XMGDjC25YG+TcBLY="

addons:
  coverity_scan:
    project:
      name: "BubbleScopeCL"
      description: "A BubbleScope 360 degree image capture and processing tool"
    notification_email: dan@dan-nixon.com
    build_command_prepend: "cmake ."
    build_command: "make -j4"
    branch_pattern: master
